### ISSUE TITLE
good job!

### ISSUE THREAD

**Issue by skatray** [Tharki-God/BetterDiscordPlugins#1]
Like [PremiumScreenShare.](https://github.com/Tharki-God/BetterDiscordPlugins/blob/master/PremiumScreenShare.plugin.js)

**Comment by Tharki-God** [comment]
> Like [PremiumScreenShare.](https://github.com/Tharki-God/BetterDiscordPlugins/blob/master/PremiumScreenShare.plugin.js)

Sir just give a star to repo that works. If you have any issue than you may state it else I - shall be closing this issue.

**Comment by SammCheese** [comment]
Big Fan of this Plugin! Where did you get the idea from?

**Comment by kekkodance** [comment]
> Big Fan of the SlowmodeConfirmation Plugin! Where did you get the idea from?

HAHAAHH
