### ISSUE TITLE
could u plz make a plugin that unlock upload 100mb limit?

### ISSUE THREAD

**Issue by Jizzy015** [Tharki-God/BetterDiscordPlugins#10]

**Comment by Tharki-God** [comment]
There is a plugin which uploads file to Google drive and share link if that's what you need

**Comment by Jizzy015** [comment]
what's that tho

**Comment by Tharki-God** [comment]
yes

**Comment by Jizzy015** [comment]
> 

thanks bruh, that helps me a lot

**Comment by Jizzy015** [comment]
> 

but when i downlaoded it in my plugins file folder,it was said that  there was a error it could not be fired.What should i do to solve it?

**Comment by Jizzy015** [comment]
> 

TypeError: Cannot read property 'subscribe' of undefined
    at new w (betterdiscord://plugins/MagicUpload.plugin.js:9:245)
    at Object.load (betterdiscord://plugins/MagicUpload.plugin.js:9:9437)
    at Object.initializeAddon (<anonymous>:4:42101)
    at Object.loadAddon (<anonymous>:4:8923)
    at Object.loadAddon (<anonymous>:4:40648)
    at FSWatcher.<anonymous> (<anonymous>:4:6907)

**Comment by Jizzy015** [comment]
> > 
> 
> 谢谢bruh，这对我有很大帮助

here is what it said

**Comment by Tharki-God** [comment]
> > > 
> > 
> > but when i downlaoded it in my plugins file folder,it was said that there was a error it could not be fired.What should i do to solve it?
> 
> Well, first of all it's not his plugin, so if you're having a problem with the Google Drive plugin why not open an issue in the right repo? Second of all, the plugin is working fine for me, you probably did something wrong while installing it. Make sure you install it the right way then restart your client, if you still can't load the plugin you can [open an issue there](https://github.com/mack/magic-upload/issues/new/choose), not here.

Damn
