### ISSUE TITLE
Feature Request: Hide "x Blocked Messages - Show Messages" popup

### ISSUE THREAD

**Issue by Avnsx** [Tharki-God/BetterDiscordPlugins#100]
I never understood why I still get the choice to see the blocked users messages after I've blocked them, in first place.

Would be cool if you could make a plugin that removes that blocked notification too, so we can just forget about people we block entirely.

I'm not really the only person that wanted this or came up with this for the first time either lol

https://www.reddit.com/r/discordapp/comments/mv4c7v/feature_request_hide_blocked_messages/

Discord just doesn't care

**Comment by Tharki-God** [comment]
https://github.com/mwittrien/BetterDiscordAddons/blob/9bb0c60b59cfc23f6abed8f81c5dddc18ecafa7c/Plugins/RemoveBlockedUsers/RemoveBlockedUsers.plugin.js

**Comment by Avnsx** [comment]
Man google really needs to stop censoring stuff / index stuff more proefficently

Can you just delete this issue ticket, it's just cringe now

**Comment by Tharki-God** [comment]
> Man google really needs to stop censoring stuff / index stuff more proefficently
> 
> Can you just delete this issue ticket, it's just cringe now

I like it so no
