### ISSUE TITLE
Idea for a Voice Server Plugin

### ISSUE THREAD

**Issue by mutschistink** [Tharki-God/BetterDiscordPlugins#101]
A plugin where you can choose the voice servers that u usually can't choose like Frankfurt

**Comment by Tharki-God** [comment]
i dont think so its possible
any evidence to back it up?

**Comment by mutschistink** [comment]
doesn't seem like you can choose frankfurt 
![image](https://user-images.githubusercontent.com/118598934/218333074-613b7499-9a71-462b-b3bc-1e04ad4b3b44.png)

**Comment by Tharki-God** [comment]
because those are the only options for where discord servers are psychically available

**Comment by mutschistink** [comment]
Wait.. what are the none selectables then?
imaginary Servers?

**Comment by Tharki-God** [comment]
> Wait.. what are the none selectables then? imaginary Servers?

ye

**Comment by mutschistink** [comment]
no really explainm what you mean?? are they temporarely hosted? on someones pc??

**Comment by Tharki-God** [comment]
They don't exist or else it would give options
