### ISSUE TITLE
bug of fake deafen

### ISSUE THREAD

**Issue by speedlorenzo12** [Tharki-God/BetterDiscordPlugins#106]
fake deafen dont works for example in italian language of discord the button of the avatar disappear

**Comment by Tharki-God** [comment]
What?

**Comment by speedlorenzo12** [comment]
Near the button of impostations (the gear)

**Comment by Tharki-God** [comment]
> Near the button of impostations (the gear)

Can you explain what's the problem in a language I can understand?

**Comment by speedlorenzo12** [comment]
an example of what I mean 
![IMG_20230228_062846.png](https://user-images.githubusercontent.com/111771663/221762489-73186c40-3d67-42d5-855e-0826b026a4f0.png)

**Comment by Tharki-God** [comment]
You mean the button doesn't show up I see

**Comment by speedlorenzo12** [comment]
Works only in english

**Comment by Tharki-God** [comment]
> Works only in english 

Well ig I know the issue will fix it when I get back on pc
