### ISSUE TITLE
discord update

### ISSUE THREAD

**Issue by speedlorenzo12** [Tharki-God/BetterDiscordPlugins#107]
due to the new discord update, some of the plugins i use from this repository crash badly, i just warned about the update

**Comment by Tharki-God** [comment]
Which plugins to be exact

**Comment by apeRTL** [comment]
for me it wasnt none of the plugins but Amoled-Core theme, after removing everything discord still crashes when attempting to get into settings so it could be just betterdiscord-breaking update for discord

**Comment by Tharki-God** [comment]
Wait for fix by betterdiscord officially

**Comment by apeRTL** [comment]
nvm i just found out that there is a patch available on their server. (https://canary.discord.com/channels/86004744966914048/1031774670405501018/1080321844080558160)
everything is working for me

**Comment by speedlorenzo12** [comment]
For now i find bd crasher

**Comment by Tharki-God** [comment]
I mean it's supposed to crash bd

**Comment by speedlorenzo12** [comment]
Crash discord

**Comment by speedlorenzo12** [comment]
When i return to home i test the plugins

**Comment by Tharki-God** [comment]
bd pushed update to fix, if everything works then should i close the issue? test and let me know

**Comment by speedlorenzo12** [comment]
Tomorrow :) 👍

**Comment by speedlorenzo12** [comment]
for me works bye

**Comment by slysnake96** [comment]
> bd pushed update to fix, if everything works then should i close the issue? test and let me know

Works fine for me now, thanks dude.

**Comment by Tharki-God** [comment]
Should I close the issue then? Yes or no poll

**Comment by slysnake96** [comment]
Yes
