### ISSUE TITLE
bug of discord bypasses

### ISSUE THREAD

**Issue by speedlorenzo12** [Tharki-God/BetterDiscordPlugins#110]
I don't know the logical reason but when I activate discord bypasses some guilds give dots of fake new messages, an example of these guilds is goosemod

**Comment by Tharki-God** [comment]
Example?

**Comment by speedlorenzo12** [comment]
Goosemod is a guild when i active this plugin creates a false notific

**Comment by Tharki-God** [comment]
> Goosemod is a guild when i active this plugin creates a false notific

Can you specify which module of discord bypasses to be exact

**Comment by speedlorenzo12** [comment]
it is that it is difficult to understand what generates this anomaly the strange ear which is then the active plugin that does this

**Comment by speedlorenzo12** [comment]
probably is a experiment but idk, if i disable the ability to see the experiments this bug works
