### ISSUE TITLE
i have a quetion about discord bypasses

### ISSUE THREAD

**Issue by speedlorenzo12** [Tharki-God/BetterDiscordPlugins#111]
I don't know if it's a bug generated by myself from the plugin itself but the experiment mode works perfectly but when you try to remove some of the above experiments they don't remove and come back on restarting discord, the problem is that the guild unreads experiment causes to make me post new messages in the guild area that don't actually exist. what can I do? and I don't know where to get support

**Comment by Tharki-God** [comment]
dont use the plugin ez life

**Comment by Tharki-God** [comment]
Experiments have their name for a reason. Its not meant to be used by average user

**Comment by speedlorenzo12** [comment]
Ok but dont have sense of have control of your settings

**Comment by Tharki-God** [comment]
> Ok but dont have sense of have control of your settings

Not my problem. I don't use better discord anymore anyways. Use replugged it's better

**Comment by mutschistink** [comment]
> > Ok but dont have sense of have control of your settings
> 
> Not my problem. I don't use better discord anymore anyways. Use replugged it's better

why exactly did you stop using BD ?

**Comment by Tharki-God** [comment]
> > > Ok but dont have sense of have control of your settings
> > 
> > Not my problem. I don't use better discord anymore anyways. Use replugged it's better
> 
> why exactly did you stop using BD ?

Because it used to lag unlike replugged for me

**Comment by mutschistink** [comment]
> > > > Ok but dont have sense of have control of your settings
> > > 
> > > 
> > > Not my problem. I don't use better discord anymore anyways. Use replugged it's better
> > 
> > 
> > why exactly did you stop using BD ?
> 
> Because it used to lag unlike replugged for me

ah ok but is it better?

**Comment by Tharki-God** [comment]
> > > > > Ok but dont have sense of have control of your settings
> > > > 
> > > > 
> > > > Not my problem. I don't use better discord anymore anyways. Use replugged it's better
> > > 
> > > 
> > > why exactly did you stop using BD ?
> > 
> > Because it used to lag unlike replugged for me
> 
> ah ok but is it better?

I think yeah
