### ISSUE TITLE
Plugin Request

### ISSUE THREAD

**Issue by I2pRandom** [Tharki-God/BetterDiscordPlugins#114]
Is it possible for you to make a plugin that automatically blocks the new TOS agreement popup. 
I've found the parent element for the prompt.

> ` <div class="layerContainer-2lfOPe">`

I'm currently deleting it manually in my client. 
But they seem to be using JavaScript or something to block certain buttons from being used like screen-sharing.

**Comment by Tharki-God** [comment]
Use css and do display: none; on it

**Comment by karimawii** [comment]
Add this to your custom CSS tab in BD settings
I don't know if your selector is the right one though, if it's right that'll work

```css
.layerContainer-2lfOPe{
    display: none;
}
```

**Comment by karimawii** [comment]
Could you explain what you mean?

**Comment by I2pRandom** [comment]
> Could you explain what you mean?
When i don't load the element, to bypass agreeing to the new TOS certain functionality like screen-sharing, rightclicking on a group chat to leave it, even trying to open the drop down menu to delete a message do not work. there is more functionality that is disabled, but it's actually a fairly large list. I also have to spam open the console of discord before it completely loads or i get locked out of it.

**Comment by karimawii** [comment]
You know you could just agree to the new ToS right? 🙃

**Comment by karimawii** [comment]
Also we did what we could but I don't think Ahlawat will make a plugin for that, so either you agree to the new ToS or just try and do it yourself.

**Comment by Tharki-God** [comment]
just uninstall discord and get some bitches
