### ISSUE TITLE
Problems with the plugin PremiumScreenShare

### ISSUE THREAD

**Issue by CodebreakerDevESP** [Tharki-God/BetterDiscordPlugins#12]
Good morning/afternoon/evening.

I have a problem with the PremiumScreenShare plugin.

Look, when I stream with the plugin, the stream (usually in Source, 1080p or even 720p at 60 fps or 30 fps) is quite choppy (for example I stream a football match, the players are cutting between FPS).

Can there be a solution for that?

P.S Apart from that I have a good internet connection and also this normally doesn't happen with the plugin deactivated... and sorry for my bad explanation, I don't know how to explain the name of the bug.

**Comment by Tharki-God** [comment]
Can't replicate the issue

**Comment by CodebreakerDevESP** [comment]
> Can't replicate the issue

I don't really understand what you are saying, can't you answer the message? I'm new to Github and I don't know how to do that ^^''

**Comment by Tharki-God** [comment]
What

**Comment by CodebreakerDevESP** [comment]
> What

Sorry, I misunderstood the English sentence (as I said sorry for my English).

But to the question: 

I don't quite understand what you can't replicate the topic with. what does it mean?

**Comment by CodebreakerDevESP** [comment]
> > What
> 
> Sorry, I misunderstood the English sentence (as I said sorry for my English).
> 
> But to the question:
> 
> I don't quite understand what you can't replicate the topic with. what does it mean?

issue*

**Comment by Tharki-God** [comment]
I am not having the issue you are telling

**Comment by CodebreakerDevESP** [comment]
> I am not having the issue you are telling

Strange...

Does the plugin work well for you when you transmit it?
No frame drops or something like that?

**Comment by CodebreakerDevESP** [comment]
Or have you heard of people having the same thing happen to them as I have somewhere?

**Comment by Tharki-God** [comment]
Just my hardwares hold it back

**Comment by CodebreakerDevESP** [comment]
> Just my hardwares hold it back

For me, it's a little weird. Because with the plugin it has happened to me that there are strange frames. I don't really know how to explain it. I wouldn't say it was frame drops but something like frames are cut off.

Isn't there a solution or alternative options for the plugin for that?

**Comment by Tharki-God** [comment]
No

**Comment by CodebreakerDevESP** [comment]
Okey, thanks! nwn
