### ISSUE TITLE
Vanilla Loader Crashes Discord Client

### ISSUE THREAD

**Issue by zluckytraveler** [Tharki-God/BetterDiscordPlugins#13]
When selecting "Load Vanilla" from the home button the Discord Client just crashes and closes the application.

**Comment by Tharki-God** [comment]
Mac?

**Comment by zluckytraveler** [comment]
> Mac?

Yes

**Comment by Tharki-God** [comment]
Understandable have a great day

**Comment by Tharki-God** [comment]
fixed in latest update
