### ISSUE TITLE
[DiscordBypass] Experiments Dissappear Randomly

### ISSUE THREAD

**Issue by karimawii** [Tharki-God/BetterDiscordPlugins#14]
Hey, I know the whole Experiments situation, Discord is intentionally fucking it up for plugin developers to enable experiments. There's bug for the experiments part in DiscordBypass where Experiments just stop working, every enabled experiment just disappears, the experiments tab is still in the settings menu, but it doesn't let you change bucket overrides, it works again by reloading the plugin and the client, but if there's a way you can fix that, would be awesome, thanks.

**Comment by Tharki-God** [comment]
Lol

**Comment by JustOptimize** [comment]
This is the error that appears when enabling/disabling the experiments: `Uncaught TypeError: Cannot read property 'hasLoadedExperiments' of undefined`
