### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Gam3rrXD** [Tharki-God/BetterDiscordPlugins#16]
This plugin seems to interfere with the messageloggerv2 plugin. I don't exactly know why but it does prevent it from saving the edits/deletes. Please take a look :)

**Comment by Tharki-God** [comment]
Which plugin and you sure it's not issue with message logger

**Comment by adsdawdfawdcwacdaw** [comment]
Message hider, I'm having the issue too.

Can't see edits in chat either

**Comment by Gam3rrXD** [comment]
BetterRedux, checked messagelogger and no issues there

**Comment by Tharki-God** [comment]
Even if I disable message hider the message logger show same response so maybe it's a problem with message logger

**Comment by Gam3rrXD** [comment]
yea lets see

**Comment by Gam3rrXD** [comment]
and also BetterEval has the issue

**Comment by Tharki-God** [comment]
> and also BetterEval has the issue

What issue

**Comment by Gam3rrXD** [comment]
same one with message logger where its interfering

**Comment by Gam3rrXD** [comment]
let me try with the updated one

**Comment by Gam3rrXD** [comment]
Fixed with new messagelogger :)
