### ISSUE TITLE
Plugin Bugs

### ISSUE THREAD

**Issue by adsdawdfawdcwacdaw** [Tharki-God/BetterDiscordPlugins#17]
MessageHider: Prevents MessageLoggerV2 from functioning properly, stops it from logging deletes and edits as well as viewing them in chat

MessageHider (Feedback): Please make hidden messages stay hidden across sessions with a txt file to save them in.

FakeDeafen: The settings for this plugin are not persistent, the only thing that saves after restarting is the hot key, if I reload my client video gets enabled again and the user panel toggle which I had disabled.

**Comment by Tharki-God** [comment]
Regarding fake deafen it's fixed in latest build of zeres plugin library which is not released yet so wait for it. And I will test message hider issue

**Comment by Tharki-God** [comment]
It's issue with message logger not my plugin

**Comment by adsdawdfawdcwacdaw** [comment]
What about making message hider hide messages permanently?

**Comment by Tharki-God** [comment]
> What about making message hider hide messages permanently? 

Not gonna make that
