### ISSUE TITLE
FriendInvites conflicts with GFR

### ISSUE THREAD

**Issue by Serega007RU** [Tharki-God/BetterDiscordPlugins#18]
FriendInvites conflicts with [GuildAndFriendRemovalAlerts](https://github.com/Metalloriff/BetterDiscordPlugins/tree/master/GuildAndFriendRemovalAlerts) on the Direct Messages button, GFR adds its context menu there. FriendInvites makes it impossible to access the GFR context menu

![image](https://user-images.githubusercontent.com/64780091/187122211-cd418e4b-5c84-450c-80fe-647cb0259867.png)

**Comment by Tharki-God** [comment]
Then use some alternative plugin

**Comment by Serega007RU** [comment]
Can you suggest any specific alternatives?

**Comment by Tharki-God** [comment]
https://github.com/HypedDomi/BetterDiscordStuff/blob/61a9c4520a90c2370fc5103747b3cc5a34e8ef0f/Plugins/FriendCodes/FriendCodes.plugin.js

**Comment by Tharki-God** [comment]
And add a issue in GFR Repo for capability with my plugins

**Comment by Tharki-God** [comment]
> > FriendInvites conflicts with [GuildAndFriendRemovalAlerts](https://github.com/Metalloriff/BetterDiscordPlugins/tree/master/GuildAndFriendRemovalAlerts) on the Direct Messages button, GFR adds its context menu there. FriendInvites makes it impossible to access the GFR context menu
> > ![image](https://user-images.githubusercontent.com/64780091/187122211-cd418e4b-5c84-450c-80fe-647cb0259867.png)
> 
> Idk if this is just my discord that does that, but when I right click to the very left I can access gfr logs, and FriendInvites by right clicking the discord icon itself.
> 
> ![Discord_cSwxutjWLJ](https://user-images.githubusercontent.com/69881381/187293881-1c67d835-967f-4c3f-b289-472ef02e460d.gif) [ ![Discord_cSwxutjWLJ](https://user-images.githubusercontent.com/69881381/187293881-1c67d835-967f-4c3f-b289-472ef02e460d.gif) ](https://user-images.githubusercontent.com/69881381/187293881-1c67d835-967f-4c3f-b289-472ef02e460d.gif) [ ](https://user-images.githubusercontent.com/69881381/187293881-1c67d835-967f-4c3f-b289-472ef02e460d.gif)
fixed this

**Comment by Tharki-God** [comment]
its been long without any activity on this issue so closing it
