### ISSUE TITLE
[ISSUE] BD Github Downloader ERROR

### ISSUE THREAD

**Issue by zluckytraveler** [Tharki-God/BetterDiscordPlugins#19]
Upon client reboot or startup this error message appears. How can I fix this?

<img width="598" alt="Screen Shot 2022-08-31 at 4 43 29 AM" src="https://user-images.githubusercontent.com/97180817/187671160-a2a659ab-0e73-451b-8f71-c1789fc514fb.png">

**Comment by Tharki-God** [comment]
Can you send your plugins folder as zip

**Comment by zluckytraveler** [comment]
> Can you send your plugins folder as zip 

You mean all of my plugins and the config files, or for just this plugin? 

I've checked that there are no duplicates, especially for this plugin.

**Comment by Tharki-God** [comment]
Full plugin folder as zip

**Comment by zluckytraveler** [comment]
@Tharki-God [plugins.zip](https://github.com/Tharki-God/BetterDiscordPlugins/files/9464062/plugins.zip)

**Comment by Tharki-God** [comment]
There is a file named GithubDownloader.plugin.js in your plugin folder delete it
