### ISSUE TITLE
DiscordBypass

### ISSUE THREAD

**Issue by iGetUploaded** [Tharki-God/BetterDiscordPlugins#20]
So I'm using your bypass to test out the forums channels but I keep on getting this error.. I don't know if you can bypass it or not but if you can that would be dope.
![image](https://user-images.githubusercontent.com/54633753/187727073-fca5d610-034c-4c25-b0ca-ded6e4fa67d0.png)

**Comment by Tharki-God** [comment]
No

**Comment by Tharki-God** [comment]
What are you even trying to do

**Comment by iGetUploaded** [comment]
Forums channels are a thing now but you randomly get access to them and I was trying to see if I can bypass that and get them right away

**Comment by Tharki-God** [comment]
> Forums channels are a thing now but you randomly get access to them and I was trying to see if I can bypass that and get them right away

ask someone else i am not doing that
