### ISSUE TITLE
[DiscordBypass] MemorySeal ShowHiddenChannels lock icon disappears with the "No Push to Talk" bypass enabled

### ISSUE THREAD

**Issue by rollingmoai** [Tharki-God/BetterDiscordPlugins#21]
https://github.com/BD-MemorySeal/DevilBro-Alternatives/tree/distribution/ShowHiddenChannels

The channels here are supposed to have a lock icon. Disabling the "No Push to Talk" bypass will make it reappear:
![image](https://user-images.githubusercontent.com/75471378/188466710-05faed6e-7133-474c-8e99-73ba031d1953.png)

**Comment by Tharki-God** [comment]
unable to replicate the issue

**Comment by rollingmoai** [comment]
Minimal set of plugins to reproduce:
![image](https://user-images.githubusercontent.com/75471378/188686761-23a37165-11d2-45b9-a9d1-98a51aa40b9f.png)

1. Turn on "No push to talk" bypass and reload
2. See hidden channels lacking the lock icon

To fix:
1. Turn off "No push to talk" bypass and reload
2. See hidden channels working with the lock icon again

**Comment by Tharki-God** [comment]
It still shows lock icon for me

**Comment by JustOptimize** [comment]
Have you tried using other ShowHiddenChannels plugins? Like [this](https://github.com/JustOptimize/return-seeHiddenChannels) for example.

**Comment by rollingmoai** [comment]
I'm using the Cumcord hidden channels plugin right now, but thank you for the suggestion.

**Comment by JustOptimize** [comment]
If this solves the problem I think you can close the issue here 👍🏻

**Comment by rollingmoai** [comment]
> If this solves the problem I think you can close the issue here 👍🏻

No, the issue still persists for MemorySeal ShowHiddenChannels.

**Comment by JustOptimize** [comment]
I tried to replicate the issue but unsuccessfully; what version of discord are you using?

**Comment by rollingmoai** [comment]
![image](https://user-images.githubusercontent.com/75471378/188854979-39dfeafd-b0ed-4a2e-8e76-2e959a411e1f.png)

**Comment by JustOptimize** [comment]
Ok, I can confirm that this occurs (there was just need to restart the discord)

**Comment by rollingmoai** [comment]
> Ok, I can confirm that this occurs (there was just need to restart the discord)

Yep, as outlined in https://github.com/Tharki-God/BetterDiscordPlugins/issues/21#issuecomment-1238378332

**Comment by JustOptimize** [comment]
I looks like I can't read 🤦🏻 (I totally skipped the 2 lines above how to fix)

**Comment by JustOptimize** [comment]
Investigating I can confirm that this DevilBro plugin is a bit "ugly", the code is very confusing

The problem is that `this.can(constants_namespaceObject.Permissions.VIEW_CHANNEL, channel)` is returning true even if the channel is HIDDEN.
(This portion of code is used to check if he should hide the unread thing and add the lock)

PS: the plugin uses the same method to patch the permissions as DiscordBypass
```
async function _patchPermissionModule2() {
	external_PluginApi_namespaceObject.Patcher.after(GuildPermissions, "can", ((_, [perm]) => {
		if (perm === constants_namespaceObject.Permissions.VIEW_CHANNEL) return true;
	}));
}
```

**Comment by Tharki-God** [comment]
you should make a issue on showHiddenChannel's repo

**Comment by rollingmoai** [comment]
Are you sure this isn't something to be fixed on your side? The plugin works fine as is.

**Comment by JustOptimize** [comment]
ShowHiddenCnannels plugin fault, by not cashing the channels every plugin that modifies some kind of permission will break it

**Comment by JustOptimize** [comment]
ShowHiddenCnannels plugin fault, by not cashing the channels every plugin that modifies some kind of permission will break it (that's why a lot of people call it buggy)

**Comment by JustOptimize** [comment]
> the plugin works fine

So does this one

**Comment by Tharki-God** [comment]
> Are you sure this isn't something to be fixed on your side? The plugin works fine as is.

Yes it's fine from my side. Make a issue on show hidden channel Repo

**Comment by rollingmoai** [comment]
Just to be clear, the individual commit is not yet gone on GitHub (https://github.com/BD-MemorySeal/DevilBro-Alternatives/tree/47512d839fab6ddc3a6414e52ccbc6cedb13b0c5/ShowHiddenChannels), but I shall close this issue now as they have already nuked their plugin.

**Comment by Tharki-God** [comment]
> Just to be clear, the individual commit with shc is not yet gone on GitHub (https://github.com/BD-MemorySeal/DevilBro-Alternatives/tree/47512d839fab6ddc3a6414e52ccbc6cedb13b0c5/ShowHiddenChannels), but I shall close this issue now as they have already nuked their plugin.

https://cdn.discordapp.com/attachments/887750789781676092/1017455456224030751/ShowHiddenChannels.plugin.js
fixed version of their plugin by me

**Comment by rollingmoai** [comment]
> [cdn.discordapp.com/attachments/887750789781676092/1017455456224030751/ShowHiddenChannels.plugin.js](https://cdn.discordapp.com/attachments/887750789781676092/1017455456224030751/ShowHiddenChannels.plugin.js) fixed version of their plugin by me

Does it contain the fix for this issue?

**Comment by Tharki-God** [comment]
> > [cdn.discordapp.com/attachments/887750789781676092/1017455456224030751/ShowHiddenChannels.plugin.js](https://cdn.discordapp.com/attachments/887750789781676092/1017455456224030751/ShowHiddenChannels.plugin.js) fixed version of their plugin by me
> 
> Does it contain the fix for this issue?

Yes

**Comment by rollingmoai** [comment]
Great, thanks for the [plugin](https://github.com/Tharki-God/BetterDiscordPlugins#showhiddenchannels)!

**Comment by Tharki-God** [comment]
Hehe

**Comment by rollingmoai** [comment]
A "port" of https://github.com/discord-modifications/show-hidden-channels? 🧐

I don't care, it works anyway. Thanks again!

**Comment by Tharki-God** [comment]
Okay
