### ISSUE TITLE
it cant find the bd pluggins folder

### ISSUE THREAD

**Issue by miltoz** [Tharki-God/BetterDiscordPlugins#25]
it says: 
I can't find the BetterDiscord plugins folder. Are you sure it's even installed?
is there any way to fix this?
i already dragged it in the folder and tried repairing better discord but it wont find the folder.
please help :)

**Comment by miltoz** [comment]
is this even the right file?
`https://drive.google.com/file/d/1Phm8b10xXJSWjj_zjTJGta8ziXv3LJfo/view?usp=sharing`

**Comment by Tharki-God** [comment]
redownload the plugin and try again

**Comment by miltoz** [comment]
where?

**Comment by miltoz** [comment]
i cant find the file

**Comment by miltoz** [comment]
i just copy pasted the code and put it in a .txt and converted it to .js

**Comment by Tharki-God** [comment]
Have you tried manually pasting the file in plugins folder
