### ISSUE TITLE
[IP Plugin] Client Crashed

### ISSUE THREAD

**Issue by Bamboozul** [Tharki-God/BetterDiscordPlugins#26]
Discord crashed after using the slash IP command.
Plugin version: 1.0.4

![Screenshot 2022-09-09 195528](https://user-images.githubusercontent.com/101983929/189414508-3c7aab61-a56f-45a7-af98-1bce3a451a7b.png)
![Screenshot 2022-09-09 195230](https://user-images.githubusercontent.com/101983929/189414518-b90b1733-0057-4acd-b543-ec26ded94e1d.png)

**Comment by Tharki-God** [comment]
whats the error in console

**Comment by MrJktra** [comment]
> whats the error in console

-Could not fire before callback of default for Emotes TypeError: Cannot read property 'childrenMessageContent' of undefined.
-TypeError: Cannot read property 'replace' of null

**Comment by Tharki-God** [comment]
Idts it's error related to my plugins

**Comment by MrJktra** [comment]
> Idts it's error related to my plugins

Is there a log file or something I can show you?
Because the information contained in the console is very sensitive.

**Comment by Tharki-God** [comment]
> > Idts it's error related to my plugins
> 
> Is there a log file or something I can show you? Because the information contained in the console is very sensitive.

there is nothing sensitive, i can stream my console for you lmao

**Comment by MrJktra** [comment]
> > > Idts it's error related to my plugins
> > 
> > 
> > Is there a log file or something I can show you? Because the information contained in the console is very sensitive.
> 
> there is nothing sensitive, i can stream my console for you lmao

![Screenshot 2022-09-10 185156](https://user-images.githubusercontent.com/101983929/189493533-9782b511-be85-4ed4-97b9-73a5993b2cc2.png)

![Screenshot 2022-09-10 185142](https://user-images.githubusercontent.com/101983929/189493537-dcd94864-dfc3-4d93-bdd4-47072073bf69.png)

**Comment by Tharki-God** [comment]
The error seems related to bdfdb not my plugin

**Comment by MrJktra** [comment]
> The error seems related to bdfdb not my plugin

So you're telling me that the plugin is working with you without any issues?
And BDFDB is an important library plugin, and I'm pretty sure you have it installed.

**Comment by Tharki-God** [comment]
Idk what's the issue tbh
