### ISSUE TITLE
[MarkAllRead] Not working

### ISSUE THREAD

**Issue by MrJktra** [Tharki-God/BetterDiscordPlugins#27]
Version 1.0.9

![Screenshot 2022-09-09 230353](https://user-images.githubusercontent.com/101983929/189449234-d2abdf14-2b8d-4a29-bf59-76933580581d.png)
![Screenshot 2022-09-09 233645](https://user-images.githubusercontent.com/101983929/189449341-c35babf3-8aba-4186-9cc7-323423ed4797.png)

**Comment by Tharki-God** [comment]
Have you turned it on

**Comment by MrJktra** [comment]
> Have you turned it on

of course

![Screenshot 2022-09-10 143732](https://user-images.githubusercontent.com/101983929/189483728-fab49bb5-36cf-4f2b-be22-8f423198b19b.png)

**Comment by Tharki-God** [comment]
Any errors?

**Comment by MrJktra** [comment]
> Any errors?

None

**Comment by Tharki-God** [comment]
the mark all read show up only when there are any pings.

**Comment by MrJktra** [comment]
> the mark all read show up only when there are any pings.

Alright
