### ISSUE TITLE
[ShowHiddenChannels] Server still has the "unread" indicator even after marking as unread

### ISSUE THREAD

**Issue by rollingmoai** [Tharki-God/BetterDiscordPlugins#29]
#### Steps to reproduce
1. Go to a server with unread messages
2. Mark as Read for that server
3. See server still having the unread indicator

**Comment by Climax-Arc** [comment]
having same issue

**Comment by Obazzi** [comment]
same issue. the source of the problem is that some (only some) hidden channels are shone as having unread messages. you can right click and mark as read and it seems to work but only for the channel, the server still has the unread icon.

**Comment by Climax-Arc** [comment]
> 

found any solution?
its annoying ig
