### ISSUE TITLE
DMCA Takedown Pre-notice

### ISSUE THREAD

**Issue by localip** [Tharki-God/BetterDiscordPlugins#3]
I'll kindly ask you to take down the following plugins which belong to me under "All rights reserved." before proceeding with legal action.

This issue will be used as evidence of previous contact in a DMCA takedown notice if you fail to comply.

You have taken the following segments of code without my permission:
> https://github.com/Tharki-God/BetterDiscordPlugins/blob/master/UnlimitedBandwidth.plugin.js#L150-L154 which belongs to https://github.com/discord-modifications/better-discord-plugins/blob/master/NoBandwidthKick/NoBandwidthKick.plugin.js#L135-L139

> https://github.com/Tharki-God/BetterDiscordPlugins/blob/master/PremiumScreenShare.plugin.js#L146-L158 which belongs to https://github.com/discord-modifications/better-discord-plugins/blob/master/ScreenshareCrack/ScreenshareCrack.plugin.js#L132-L147

Not only have you used code from a project which states `All rights reserved.`, you also didn't even bother to change it up, clearly showing your infringement of copyright.

If these are taken down, I won't proceed with a DMCA takedown.

Kind regards,
eternal.

**Comment by Tharki-God** [comment]
okay removed unlimited bandwidth but I didn't know you had a better discord version for screen share crack. I got only a powercord one so made it myself actually. more like ported so added the credits for it.
btw accept the pull request and mak the move all plugins work or you can just copy my voice chat utilities plugin it got more features

**Comment by localip** [comment]
That piece of code is taken directly, so please take down the remaining plugin.

I'll review that PR later today.

**Comment by Tharki-God** [comment]
> That piece of code is taken directly, so please take down the remaining plugin.
> 
> I'll review that PR later today.

i changed the code. refractored it. its not same now

**Comment by rippedpiracy** [comment]
great way to approach a legal notice ain't it

**Comment by kekkodance** [comment]
that's an amazing way to handle a legal (100% serious) notice

**Comment by Tharki-God** [comment]
I mean it's not the same code now.

**Comment by localip** [comment]
Last chance, showing you don't care just adds more fuel to the fire for you.

**Comment by Tharki-God** [comment]
> Last chance, showing you don't care just adds more fuel to the fire for you.

i do care but its not the same code anymore. i deleted the plugin which was like that
