### ISSUE TITLE
[Suggestion] Cooperative request (SHC)

### ISSUE THREAD

**Issue by phoriah** [Tharki-God/BetterDiscordPlugins#30]
There is currently another group of people trying to fix this big issue of ShowHiddenChannels (SHC).
[here](https://github.com/Saalvage/BetterDiscordAddons)
They also have their own Discord and Subreddit dedicated to all of this (you can find it on opened issue there)
All I'm saying is if you could potentially team up with them and unite your efforts I think that'd be great.
They are also working on restoring other plugins that are / will likely be blacklisted by BetterDiscord eventually.
Just a suggestion!
Thanks, P.

**Comment by rollingmoai** [comment]
Repository is archived now 🤔

**Comment by Tharki-God** [comment]
Lmao

**Comment by Tharki-God** [comment]
what am I supposed to do?

**Comment by Tharki-God** [comment]
i am closing this as plugin aint anymore on repo
