### ISSUE TITLE
ShowHiddenChannels missing feature

### ISSUE THREAD

**Issue by yorik100** [Tharki-God/BetterDiscordPlugins#32]
It's not showing who has access to the channel by right clicking a hidden channel (there are other plugins to do that but the ShowHiddenChannels look was easier to read -> https://github.com/Saalvage/BetterDiscordAddons/blob/master/Plugins/ShowHiddenChannelsV2/ShowHiddenChannelsV2.plugin.js#L333), you can also make it so that it shows which roles and wich users are allowed and denied in a specific channel under the "This is a hidden channel." message that'd show allowed/denied roles like that ![image](https://user-images.githubusercontent.com/16320315/190277568-2fdb0f3e-96cd-4b59-b504-24a0f37d87fa.png) and allowed/denied users with their icon next to their name

And I don't know if you credited eternal https://github.com/discord-modifications/show-hidden-channels as it's a direct port from his plugin, at least it seems like it, very much

**Comment by rollingmoai** [comment]
> And I don't know if you credited eternal [discord-modifications/show-hidden-channels](https://github.com/discord-modifications/show-hidden-channels) as it's a direct port from his plugin, at least it seems like it, very much

Did you even read the readme??
![image](https://user-images.githubusercontent.com/75471378/190314450-fca34aaa-9e98-4652-b9bb-8482c09d76ac.png)

**Comment by Tharki-God** [comment]
I am not gonna add that feature

**Comment by Tharki-God** [comment]
Use permission viewer

**Comment by yorik100** [comment]
> > And I don't know if you credited eternal [discord-modifications/show-hidden-channels](https://github.com/discord-modifications/show-hidden-channels) as it's a direct port from his plugin, at least it seems like it, very much
> 
> Did you even read the readme?? ![image](https://user-images.githubusercontent.com/75471378/190314450-fca34aaa-9e98-4652-b9bb-8482c09d76ac.png)

No. That's why I said I don't know, makes sense, doesn't it?
