### ISSUE TITLE
VanillaLoader causing crash

### ISSUE THREAD

**Issue by Nanorithm** [Tharki-God/BetterDiscordPlugins#35]
![image](https://user-images.githubusercontent.com/13856563/191323869-6a963e89-5bbd-4321-805b-05546585110b.png)

![image](https://user-images.githubusercontent.com/13856563/191323847-eb60106b-194a-407e-b153-d4594a2543ef.png)

Looks like VanillaLoader is causing a crash, BD works fine if I delete the plugin and restart but as soon as I add it back and enable it, discord crashes with the above error.

**Comment by Tharki-God** [comment]
it shows error of guild and friend removal alert not vanilla loader

**Comment by Nanorithm** [comment]
I removed GFRA and put vanilla loader back and now when I hit reload vanilla it just closes discord, and when I reopen, it opens normal BD

**Comment by Tharki-God** [comment]
"Vanilla loader"

**Comment by Tharki-God** [comment]
Should be fixed in latest commit
