### ISSUE TITLE
All plugins not working after discord update 9/26

### ISSUE THREAD

**Issue by syth911** [Tharki-God/BetterDiscordPlugins#36]
![image](https://user-images.githubusercontent.com/43626918/192657674-26feb199-35ad-4301-8704-6aadc9fdfe37.png)

This^ is the error I'm getting. I downloaded this plugin because the other one I was using also broke with this update.

**Comment by Tharki-God** [comment]
It might take week or months for every plugin to get fixed so wait

**Comment by black-trush** [comment]
DiscordBypass plugin could not compiled

**Comment by JustMeWho** [comment]
![image](https://user-images.githubusercontent.com/62073281/193428149-6a3089d0-6b07-4758-8b45-681e63f12a59.png)

**Comment by Tharki-God** [comment]
lmao

**Comment by K4sum1** [comment]
Where is ShowHiddenChannels

**Comment by Banaanae** [comment]
adding on to this it would be nice to have a roadmap on what plugins have been fixed for the new update

**Comment by Tharki-God** [comment]
I will add a road map on my discord server

**Comment by Tharki-God** [comment]
all plugins have been fixed so closing the issue

**Comment by asdf2345** [comment]
Where the fuck is ShowHiddenChannels

**Comment by Tharki-God** [comment]
> Where the fuck is ShowHiddenChannels

In my plugins folder

**Comment by asdf2345** [comment]
lol

**Comment by Banaanae** [comment]
> Where the fuck is ShowHiddenChannels

https://github.com/JustOptimize/return-ShowHiddenChannels
+ no BDFDB dependency

**Comment by Tharki-God** [comment]
> > Where the fuck is ShowHiddenChannels
> 
> https://github.com/JustOptimize/return-ShowHiddenChannels
> + no BDFDB dependency 

I have better version of this if can get permission from original author

**Comment by asdf2345** [comment]
> if can get permission from original author

beta moment

**Comment by Banaanae** [comment]
> > > Where the fuck is ShowHiddenChannels
> > 
> > 
> > https://github.com/JustOptimize/return-ShowHiddenChannels
> > 
> > * no BDFDB dependency
> 
> I have better version of this if can get permission from original author

ik but you asked months ago theyre probably dead

**Comment by Tharki-God** [comment]
> > if can get permission from original author
> 
> beta moment

I am a cute femboy uwu
