### ISSUE TITLE
DiscordBypass randomly disconnecting/reconnecting me from VCs

### ISSUE THREAD

**Issue by TheWadeSmith** [Tharki-God/BetterDiscordPlugins#48]
One trigger is if I send a friend request when I'm streaming.

**Comment by TheWadeSmith** [comment]
^ or simply just sending a friend request in VC

**Comment by TheWadeSmith** [comment]
nevermind, it was the friend removal alert plugin conflicting with something

**Comment by Tharki-God** [comment]
lmao

**Comment by TheWadeSmith** [comment]
> lmao

shush, we do not speak of this. 🙃
