### ISSUE TITLE
[PremiumScreenShare] No audio when sharing

### ISSUE THREAD

**Issue by Kirushh** [Tharki-God/BetterDiscordPlugins#59]
When I share screen with this plugin, people can't hear anything, so I cant share videos, for example.

**Comment by Tharki-God** [comment]
Any errors or anything?

**Comment by Kirushh** [comment]
> Any errors or anything?

Just that, when I use the plugin, ppl cant hear the sound from my screen.

**Comment by Tharki-God** [comment]
For audio you need to stream application instead of screen

**Comment by Tharki-God** [comment]
try using only this plugin and remove all other plugin except zlib

**Comment by Tharki-God** [comment]
what other plugins are you using?

**Comment by Kirushh** [comment]
Hmm, it already works, at the end it was a discord bug, but it was coincidence that it worked well when I took out your plugin, after finding that the problem was discord, I just reinstalled it (it wasnt betterdiscord neither), sorry for bothering!
