### ISSUE TITLE
Freemoji sending 2 emojis at once.

### ISSUE THREAD

**Issue by ohitstom** [Tharki-God/BetterDiscordPlugins#6]
See title.
![image](https://user-images.githubusercontent.com/22730962/182815599-6b7a16aa-15c2-41a9-a950-b26925022f1f.png)

**Comment by ohitstom** [comment]
It also makes you send double messages

**Comment by Tharki-God** [comment]
thats not my plugin

**Comment by ohitstom** [comment]
Omg sorry I opened that on the wrong rep

**Comment by ohitstom** [comment]
Omg sorry I opened that on the wrong repo

**Comment by ohitstom** [comment]
Omg sorry I opened that on the wrong repo

**Comment by Tharki-God** [comment]
lmao
