### ISSUE TITLE
fake preview

### ISSUE THREAD

**Issue by Hunter-Matata** [Tharki-God/BetterDiscordPlugins#60]
is there a known problem with the fake preview in the discord bypasser plugin? because it won't load up.

**Comment by Tharki-God** [comment]
> is there a known problem with the fake preview in the discord bypasser plugin? because it won't load up.

can you share the custom preview link here ig there is problem with the image

**Comment by Hunter-Matata** [comment]
https://i.imgur.com/KyzDHvU.png (don't ask why lol) but I also do not have this text box thingy
![image](https://user-images.githubusercontent.com/118884892/203628959-7a01163b-679f-4910-b76a-043bf014a92b.png)

**Comment by Tharki-God** [comment]
> https://i.imgur.com/KyzDHvU.png (don't ask why lol) but I also do not have this text box thingy ![image](https://user-images.githubusercontent.com/118884892/203628959-7a01163b-679f-4910-b76a-043bf014a92b.png)

well wait for zlib fix for settings to be released, and i asked for link of the stream preview you are trying to set

**Comment by Hunter-Matata** [comment]
yeah, the link of the stream preview I try to set, is the imgur link

**Comment by Tharki-God** [comment]
i think imgur links dont work

**Comment by Pickymarker** [comment]
what links work because i got them to fix the text box thing

**Comment by Tharki-God** [comment]
> what links work because i got them to fix the text box thing

Discord cdn and github raw and github io links works as they are tested

**Comment by Tharki-God** [comment]
should i close this issue?

**Comment by RobinRMC** [comment]
I don't see a reason why Imgur links wouldn't. On top of that, I'm using an Imgur link myself and can confirm that it works just fine.

**Comment by Tharki-God** [comment]
Should be fixed with latest update
