### ISSUE TITLE
ScreenPremium

### ISSUE THREAD

**Issue by AlejoCRF** [Tharki-God/BetterDiscordPlugins#61]
Is it working this plugis?, because i try it but i cant

**Comment by Tharki-God** [comment]
Yes it's working

**Comment by FroggyRaven** [comment]
> Yes it's working

you cant open the settings

**Comment by Tharki-God** [comment]
> > Yes it's working
> 
> you cant open the settings

thats a problem with zlib not my plugin go tell [Zerebos](https://github.com/rauenzi) to release the fix

**Comment by Pickymarker** [comment]
zlib has a fixed version if you want it

**Comment by Xemacs64** [comment]
> zlib has a fixed version if you want it

Can you give me the link please?

**Comment by Pickymarker** [comment]
https://github.com/riolubruh/YABDP4Nitro/blob/main/0PluginLibrary.plugin.js

**Comment by Xemacs64** [comment]
> https://github.com/riolubruh/YABDP4Nitro/blob/main/0PluginLibrary.plugin.js

I already have that version installed, are you sure its working with YABDP4Nitro? Did you test it out with a friend? Also I think version v2.0.2would work instead, do you have that version?
