### ISSUE TITLE
cant open individual settings on premiumscreenshare and all of the home button plugins dont work when i click the home button

### ISSUE THREAD

**Issue by FroggyRaven** [Tharki-God/BetterDiscordPlugins#62]

**Comment by Tharki-God** [comment]
any errors?  and check https://github.com/Tharki-God/BetterDiscordPlugins/issues/61

**Comment by EPLOGx** [comment]
I have the same issue, I have ZLib 2.0.9 and no erros

**Comment by EPLOGx** [comment]
@Tharki-God Okay, I found the error. The plugins are not compatible with DevilBro plugins (ReadAllNotificationsButton, ServerCounter & FriendNotifications). Could you please try to make these compatible?

**Comment by Tharki-God** [comment]
Home button context menu is what you are talking about right

**Comment by EPLOGx** [comment]
> Home button context menu is what you are talking about right 

Yes

**Comment by Tharki-God** [comment]
you should maybe ask devil bro for adding capability coz i am dumb and is unable to find any fix but will still try

**Comment by EPLOGx** [comment]
Are you sure you fixed it? It still does not work for me :c

**Comment by Tharki-God** [comment]
Idk what to do then

**Comment by EPLOGx** [comment]
now it works, thanks :)

**Comment by Tharki-God** [comment]
Good to know
