### ISSUE TITLE
The options are not expanding 

### ISSUE THREAD

**Issue by nanunamzzy** [Tharki-God/BetterDiscordPlugins#63]
![image](https://user-images.githubusercontent.com/103026989/203987810-758cd12b-fe30-4c05-acf8-f027ef65e723.png)
i clicked but it's not opening :D i deleted every plugin and i installed this and same issue. pls fix tysm

**Comment by Tharki-God** [comment]
wait for zlib fix to be released

**Comment by Pickymarker** [comment]
zlib has a fixed version i you want it

**Comment by stefanaras02** [comment]
> zlib has a fixed version i you want it

I thought zlib was down? could you please send it to me?

**Comment by Tharki-God** [comment]
[the fixed version](https://cdn.discordapp.com/attachments/1038578157105717258/1046106274456162384/0PluginLibrary.plugin.js)

**Comment by nanunamzzy** [comment]
oh ty it works now :D great job brother
