### ISSUE TITLE
PremiumScreenShare Error

### ISSUE THREAD

**Issue by xiongzz15** [Tharki-God/BetterDiscordPlugins#65]
Got this error when placing Premiumscreenshare to plugin folder. Am I doing something wrong? 

![error](https://user-images.githubusercontent.com/119089763/204069507-fe424170-2c99-43c2-82dc-13fcbd7d6396.png)

**Comment by Tharki-God** [comment]
Re-download it

**Comment by xiongzz15** [comment]
uninstalled betterdiscord and reinstalled and redownloaded the plug-in , still same error :(

**Comment by Tharki-God** [comment]
Can you screenshot the content of plugin file

**Comment by xiongzz15** [comment]
Hi, do you mean the content inside the plug-in folder ?

**Comment by Pickymarker** [comment]
there is a better nitro plugin that has custom activities and custom resolution and fps and stuff if you want i can send it to you

**Comment by xiongzz15** [comment]
> there is a better nitro plugin that has custom activities and custom resolution and fps and stuff if you want i can send it to you

yes i just require the streaming option for higher fps and reso

**Comment by Tharki-God** [comment]
> there is a better nitro plugin that has custom activities and custom resolution and fps and stuff if you want i can send it to you

- [ ] Activities hmm send it

**Comment by Tharki-God** [comment]
> Hi, do you mean the content inside the plug-in folder ?

The plugin file

**Comment by xiongzz15** [comment]
[PremiumScreenShare.plugin.txt](https://github.com/Tharki-God/BetterDiscordPlugins/files/10096636/PremiumScreenShare.plugin.txt)
Like this?

**Comment by Tharki-God** [comment]
You are saving the file wrong way. Go to file click on raw and then ctrl + s

**Comment by stefanaras02** [comment]
> there is a better nitro plugin that has custom activities and custom resolution and fps and stuff if you want i can send it to you

I am also interested in the file, please send it if you can !

**Comment by xiongzz15** [comment]
omg im a noob..sry..got it working!. tq!

**Comment by Tharki-God** [comment]
i will close the issue after https://github.com/Pickymarker share the plugin for custom activities

**Comment by Pickymarker** [comment]
https://github.com/riolubruh/YABDP4Nitro
this is the best nitro plugin out there
