### ISSUE TITLE
Discord Bypass

### ISSUE THREAD

**Issue by iGetUploaded** [Tharki-God/BetterDiscordPlugins#74]
Idk if its just a bug for me or what but the custom stream preview doesnt allow me to put a custom link in 
![image](https://user-images.githubusercontent.com/54633753/206794793-c6d9cc1e-8925-4cbd-b924-b28d1bf25301.png)

**Comment by Tharki-God** [comment]
Update zeres plugin library

**Comment by iGetUploaded** [comment]
Got it to work now thanks
