### ISSUE TITLE
Plugin Suggest : Voice Channel Keybinded

### ISSUE THREAD

**Issue by albyalex96** [Tharki-God/BetterDiscordPlugins#75]
Hello. I would like to suggest a plugin that a lot of users can use , which is keybind a particular voice channel. What i've in mind is basically the following:
A setting menu to specify server , channel id of the desired voice channel and the key to bind .
This will make the life of poor people, who can't afford second monitor and don't want game crashing to alt tab, to be happy :-D

**Comment by Tharki-God** [comment]
Talked on dc not possible
