### ISSUE TITLE
MessageHider: Crash on right-click

### ISSUE THREAD

**Issue by Taizunz** [Tharki-God/BetterDiscordPlugins#76]
I think a recent Discord update changed something that now causes Discord to crash when right-clicking messages while MessageHider is enabled. Disabling the plugin and reloading Discord stops Discord from crashing on right-clicking.

Build info if needed:
Stable 163880 (4ef3df8) 
Host 1.0.9008 (27798) 
Windows 10 64-Bit (10.0.19044)

**Comment by MichaelDavidGK** [comment]
Crash when opening context menu was related to BD itself and has been fixed in version 1.8.4 released yesterday (around 13 hours after this issue was opened)
