### ISSUE TITLE
Discord bypass crashing

### ISSUE THREAD

**Issue by rollingmoai** [Tharki-God/BetterDiscordPlugins#77]
![image](https://user-images.githubusercontent.com/75471378/207768536-51c7865d-c2e4-403b-a0b3-cb3eba0afad0.png)

**Build info**
Ptb 164312 (c8404f6)
Host 1.0.1023
Windows 10 64-Bit (10.0.22621)

**Comment by XxUnkn0wnxX** [comment]
yep same here..

**Comment by Doomelf** [comment]
Experiencing this as well. Other plugins are working as expected, but enabling this one crashes Discord over and over on startup with only solution being to repair BetterDiscord with executable and leave this plugin disabled.

**Comment by mutschistink** [comment]
exactly the same i guess we are just gonna need to wait

**Comment by mutschistink** [comment]
> Discord made changes so Experiments will crash, if you remove it from code, everything else works ;)

what do you mean? how do you do that?

**Comment by MichaelDavidGK** [comment]
> > Discord made changes so Experiments will crash, if you remove it from code, everything else works ;)
> 
> what do you mean? how do you do that?

Comment out lines 418-439 using /* */
i.e.:
/*line1
line2
line3*/

**Comment by JustOptimize** [comment]
> Comment out lines 418-439 using /* */

Or just comment out line 364 :/

**Comment by MichaelDavidGK** [comment]
> > Comment out lines 418-439 using /* */
> 
> Or just comment out line 364 :/

Well, ye, i was just trying to fix it.
That's why I gave those lines, but apparently I am too lazy to care and fix another error that i get after fixing this :P

**Comment by unrelatedact** [comment]
You could also just change `"experiments": true` to `false` in the DiscordBypass config file if its enabled.

At least that's what worked for me

**Comment by Tharki-God** [comment]
It will be fixed in next update wait for it

**Comment by flezus** [comment]
I believe Discord updated again, the plugin crashed again.

**Comment by Tharki-God** [comment]
should be fixed now
