### ISSUE TITLE
[StatisticsCounter] Context Menu Crashes Discord

### ISSUE THREAD

**Issue by karimawii** [Tharki-God/BetterDiscordPlugins#78]
When I right-click the counter, it crashes the client.

### Reproduction:
1. Right-click the counter

it's one step lmao
(also thanks for maintaining this repo, I know how hard it can get sometimes, but you're bossing it so far, keep going 💪🏻 )

**Comment by Tharki-God** [comment]
will try to fix with next update

**Comment by Tharki-God** [comment]
turns out its a bug with bd itself so wait for them to fix it instead of me

**Comment by Tharki-God** [comment]
https://github.com/BetterDiscord/BetterDiscord/issues/1507

**Comment by karimawii** [comment]
💯 

![image](https://user-images.githubusercontent.com/69881381/211603099-7ff0f9e0-e72e-4086-a35d-bb21e503076e.png)
