### ISSUE TITLE
[Enhancement][StatisticsCounter] Add a slider for font size

### ISSUE THREAD

**Issue by karimawii** [Tharki-God/BetterDiscordPlugins#79]
On my laptop, the screen is smaller, so the counters appear stacked where the number is under the name of the counter, it looks kinda ugly and takes double the space, so I have to go into the code and edit the font sizes of the counters after every update, but I think implementing a slider would be useful, thanks.

**Comment by Tharki-God** [comment]
nice idea

**Comment by Tharki-God** [comment]
Should I make it slider or number only input?

**Comment by karimawii** [comment]
Like the duration slider, I think it should scale all the cou ter font sizes at once while keeping the difference between them, so that way it's consistent and you don't have a slider for each counter

**Comment by Tharki-God** [comment]
from what to what should be the slider ? i am keeping it from 5 to 20 for now

**Comment by karimawii** [comment]
yeah that'll do, lowest one I have is 7.5, highest one is 10.5

**Comment by Tharki-God** [comment]
done with latest update
