### ISSUE TITLE
Feature Request: Unlock Animated Emotes for non nitro users

### ISSUE THREAD

**Issue by Avnsx** [Tharki-God/BetterDiscordPlugins#82]
The more nitro features we unlock for non nitro users, the better? 🤗

More specifically I'm talking about the animated emotes, people upload into their servers.
Those do not seem useable (not even within that specific server), if you've not paid for nitro.

**Comment by Tharki-God** [comment]
Use freemoji of some shit

**Comment by Tharki-God** [comment]
Should I close the issue?
