### ISSUE TITLE
Fake Deafen Crashing

### ISSUE THREAD

**Issue by iGetUploaded** [Tharki-God/BetterDiscordPlugins#84]
Got the new Library for your plugins and now *fake deafen* crashes every time I load up

**Comment by Pickymarker** [comment]
same for me

**Comment by Pickymarker** [comment]
user panel on fake deafen is causing the crash

**Comment by Tharki-God** [comment]
unable to replicate the issue, please share if any errors are there

**Comment by iGetUploaded** [comment]
> unable to replicate the issue, please share if any errors are there


https://user-images.githubusercontent.com/54633753/209595429-8807f82d-797a-42c8-8fe2-6dc7ef2c7c61.mp4

**Comment by iGetUploaded** [comment]
hopefully that helps

**Comment by Pickymarker** [comment]
https://user-images.githubusercontent.com/74084396/209596579-0993f4fe-4f56-44ad-bdef-10781fb08398.mp4

here is me showing it happening

**Comment by Pickymarker** [comment]
then after it says there's a update on the plugin but its just the same one and the only way to have it not crash is to delete the json file then not turn on userpanel

**Comment by MichaelDavidGK** [comment]
It works after update, but icon is always crossed no matter if it's faked or not

**Comment by iGetUploaded** [comment]
> It works after update, but icon is always crossed no matter if it's faked or not

Works for me now idk why it was crashing before
