### ISSUE TITLE
BunnyLib Bug

### ISSUE THREAD

**Issue by zuzumi-f** [Tharki-God/BetterDiscordPlugins#85]
The library won't let you go home after going to a server.
Clicks on the home button do nothing, it rarely returns to a clickable state but most of the time you just can't go back.
![Discord_UEpNFDECSJ](https://user-images.githubusercontent.com/79029257/209823601-005947bc-576e-488a-b96f-610f93426475.gif)

**Comment by Tharki-God** [comment]
Try disabling all other plugins

**Comment by zuzumi-f** [comment]
okay, it seems that BunnyLib is not compatible with [OnlineFriendCount](https://github.com/Zerthox/BetterDiscord-Plugins/blob/master/dist/bd/OnlineFriendCount.plugin.js) an official plugin of BD
is it possible for you to make it compatible?

**Comment by Tharki-God** [comment]
> okay, it seems that BunnyLib is not compatible with [OnlineFriendCount](https://github.com/Zerthox/BetterDiscord-Plugins/blob/master/dist/bd/OnlineFriendCount.plugin.js) an official plugin of BD
> is it possible for you to make it compatible?

Use statistics counter plugin instead

**Comment by zuzumi-f** [comment]
sure, why not
