### ISSUE TITLE
)

### ISSUE THREAD

**Issue by Haganaki** [Tharki-God/BetterDiscordPlugins#88]
![1](https://user-images.githubusercontent.com/94139573/210190608-c5ffdf13-5021-467d-aec6-ce9811ff87a7.png)

**Comment by Tharki-God** [comment]
What?

**Comment by Haganaki** [comment]
> What?

sry, just find it funny that u put it here )

**Comment by Tharki-God** [comment]
> > What?
> 
> sry, just find it funny that u put it here )

Oh lol
