### ISSUE TITLE
simple question

### ISSUE THREAD

**Issue by pedritoelcrack** [Tharki-God/BetterDiscordPlugins#90]
what is this?

https://github.com/Tharki-God/BetterDiscordPlugins/blob/4c3d1e7a54c3d4e0602e3cbc1395eb2d82313406/1BunnyLib.plugin.js#L2001

https://github.com/Tharki-God/BetterDiscordPlugins/blob/4c3d1e7a54c3d4e0602e3cbc1395eb2d82313406/1BunnyLib.plugin.js#L2064

**Comment by slysnake96** [comment]
Check closed issues first, These are simply just jokes that the creator put in there.
At least that is the gist of it from what I read in the closed issues.

https://github.com/Tharki-God/BetterDiscordPlugins/issues/88#issue-1515955990

**Comment by Tharki-God** [comment]
> what is this?
> 
> https://github.com/Tharki-God/BetterDiscordPlugins/blob/4c3d1e7a54c3d4e0602e3cbc1395eb2d82313406/1BunnyLib.plugin.js#L2001
> 
> https://github.com/Tharki-God/BetterDiscordPlugins/blob/4c3d1e7a54c3d4e0602e3cbc1395eb2d82313406/1BunnyLib.plugin.js#L2064

jokes, got you
