### ISSUE TITLE
Idea for dc bypasses

### ISSUE THREAD

**Issue by mutschistink** [Tharki-God/BetterDiscordPlugins#98]
a bypass for the "Spotify is running for 30 seconds so imma gonna start acting like i care about them" warning

**Comment by Tharki-God** [comment]
what do you even mean?

**Comment by mutschistink** [comment]
> what do you even mean?

https://support.discord.com/hc/en-us/articles/115002872212-Spotify-Auto-Pause

**Comment by Tharki-God** [comment]
you want to stop that from happening?

**Comment by mutschistink** [comment]
> you want to stop that from happening?

yes

**Comment by Tharki-God** [comment]
> > you want to stop that from happening?
> 
> yes

https://github.com/bepvte/bd-addons/blob/a80fc0f6122bafa68113d8b8513ad07eeeaf0792/plugins/NoSpotifyPause.plugin.js

**Comment by mutschistink** [comment]
> > > you want to stop that from happening?
> > 
> > 
> > yes
> 
> https://github.com/bepvte/bd-addons/blob/a80fc0f6122bafa68113d8b8513ad07eeeaf0792/plugins/NoSpotifyPause.plugin.js

holy i luv you :0 thx

**Comment by Tharki-God** [comment]
will add it into discord bypass aswell ig

**Comment by Tharki-God** [comment]
done
