### ISSUE TITLE
BunnyLib does way too many requests to tharki-god.github.io/

### ISSUE THREAD

**Issue by MGThePro** [Tharki-God/BetterDiscordPlugins#99]
BunnyLib was the only plugin from you that was enabled, and my local pihole counts 2602 total queries to your github page.

That is **A LOT**

For context, it counted a total of 5300 queries from my machine total. So almost half of all my queries were to your github page.

Afaik all this data collected by pihole is only over the last 24 hours, of which my PC was only running for around half.

That is like 3 queries per minute on average.

EDIT: I forgot about my second discord instance which was running BunnyLib and FakeDeafen.

So 2x BunnyLib and 1x FakeDeafen resulted in around 3 requests per minute, which is still too much

**Comment by Tharki-God** [comment]
Which links to be exact?

**Comment by MGThePro** [comment]
I don't know, DNS queries only include the domain and no paths

**Comment by Tharki-God** [comment]
I can't stop it from making request if I don't know which link it is

**Comment by MGThePro** [comment]
And what do you expect me to do? The entire traffic is TLS encrypted so I cant exactly just look at it through wireshark

**Comment by Tharki-God** [comment]
> And what do you expect me to do? The entire traffic is TLS encrypted so I cant exactly just look at it through wireshark

what do you expect me to do? resolve the issue without knowing where the problem originates from?

**Comment by Tharki-God** [comment]
unable to replicate the issue

**Comment by Tharki-God** [comment]
should be fixed in latest bunny lib, will make only 1 req every 10 mins now

**Comment by Tharki-God** [comment]
test and let me know if i should close the issue @MGThePro

**Comment by MGThePro** [comment]
after a couple of days of testing your domain is at just 53 hits, and that is with two plugins enabled on two seperate instances. So I'd consider this fixed now.

**Comment by Tharki-God** [comment]
Yeah a update check for all plugins every 10 mins
